const defaultCards = [
  ['Wat is het eerste verzoek in het modelgebed?','Dat Gods naam geheiligd wordt.','Jezus leert zijn discipelen om de reputatie en heiligheid van zijn Vaders naam vóór persoonlijke behoeften te plaatsen.','Mattheüs 6:9'],
  ['Wie bouwde de ark?','Noach.','God vroeg Noach een ark te bouwen om zijn gezin en de dieren tijdens de vloed te beschermen.','Genesis 6:13-22'],
  ['Wie werd gevraagd zijn land te verlaten om naar een land te gaan dat God hem zou tonen?','Abraham.','Jehovah beloofde Abraham een grote natie te maken en mensen uit alle naties door zijn nageslacht te zegenen.','Genesis 12:1-3'],
  ['Wie ontving de Tien Geboden op de berg Sinaï?','Mozes.','Nadat Jehovah de Israëlieten uit Egypte had bevrijd, gaf hij hun via Mozes zijn Wet.','Exodus 19:20; 20:1-17'],
  ['Welke jonge herder versloeg Goliath?','David.','David ging de Filistijnse reus met een slinger tegemoet, overtuigd dat de overwinning van Jehovah kwam.','1 Samuël 17:45-50'],
  ['Wie werd in een leeuwenkuil geworpen omdat hij tot zijn God bad?','Daniël.','Daniël bleef tot Jehovah bidden ondanks een koninklijk bevel en werd tegen de leeuwen beschermd.','Daniël 6:10, 16-23'],
  ['Welke profeet werd door een grote vis opgeslokt?','Jona.','Jona vluchtte eerst voor zijn opdracht, maar predikte daarna tot de inwoners van Ninevé.','Jona 1:17; 3:1-5'],
  ['In welke stad werd Jezus geboren?','Bethlehem.','Jezus werd geboren in Bethlehem, zoals de profetie had aangekondigd.','Mattheüs 2:1; Micha 5:2'],
  ['Wat is het grootste gebod?','Jehovah liefhebben met heel je hart, ziel en verstand.','Jezus liet zien dat liefde voor God het belangrijkste gebod is.','Mattheüs 22:37, 38'],
  ['Welk gebod is vergelijkbaar met het grootste gebod?','Je naaste liefhebben als jezelf.','Liefde voor God blijkt uit de manier waarop we anderen behandelen.','Mattheüs 22:39, 40'],
  ['Welke discipel liep over het water naar Jezus?','Petrus.','Petrus begon over het water te lopen, maar werd bang door de storm en Jezus hielp hem.','Mattheüs 14:28-31'],
  ['Wie doopte Jezus?','Johannes de Doper.','Jezus liet zich in de Jordaan dopen en Gods geest daalde op hem neer.','Mattheüs 3:13-17'],
  ['Wat is de gulden regel die Jezus leerde?','Behandel anderen zoals je zelf behandeld wilt worden.','Deze regel vat de geest van de Wet en de Profeten samen in menselijke relaties.','Mattheüs 7:12'],
  ['Welke apostel vervolgde eerst christenen voordat hij Paulus werd genoemd?','Saulus van Tarsus.','Op weg naar Damaskus ontmoette Saulus de verheerlijkte Jezus en werd hij een ijverige verkondiger van het goede nieuws.','Handelingen 9:1-22'],
  ['Welke vrucht van de geest wordt als eerste genoemd?','Liefde.','Paulus noemt eigenschappen die Gods geest in het leven van christenen voortbrengt.','Galaten 5:22, 23'],
  ['Wat belooft Openbaring 21:4?','God zal elke traan afwissen; dood, rouw, verdriet en pijn zullen verdwijnen.','Dit visioen toont de prachtige toekomst die God voor trouwe mensen belooft.','Openbaring 21:3, 4'],
  ['Welke naam van God werd aan Mozes bekendgemaakt?','Jehovah.','God legde Mozes uit dat zijn naam verbonden is met zijn voornemen en zijn vermogen te worden wat hij besluit te worden.','Exodus 3:14, 15'],
  ['Wat betekent geloof hebben?','Zeker zijn van wat je hoopt en overtuigd zijn van onzichtbare werkelijkheden.','Geloof rust op goede redenen en zet ons ertoe aan volgens Gods beloften te handelen.','Hebreeën 11:1'],
  ['Waarom kwam Jezus naar de aarde?','Om zijn leven te geven als losprijs voor velen.','Door zijn offer maakte Jezus bevrijding van zonde en dood mogelijk.','Mattheüs 20:28'],
  ['Welke eigenschappen moedigt Paulus christenen aan tegenover anderen te tonen?','Nederigheid, zachtaardigheid en geduld.','Paulus moedigt christenen aan Gods persoonlijkheid na te volgen in hun omgang met anderen.','Kolossenzen 3:12, 13']
].map(([question,answer,context,verse])=>({question,answer,context,verse}));

const $=id=>document.getElementById(id);
let cards=loadDeck(); let index=Number(localStorage.getItem('bijbelQuizIndex'))||0; let known=new Set(JSON.parse(localStorage.getItem('bijbelQuizKnown')||'[]'));
const flashcard=$('flashcard');
function loadDeck(){try{const saved=JSON.parse(localStorage.getItem('bijbelQuizDeck'));return Array.isArray(saved)&&saved.length?saved:defaultCards;}catch{return defaultCards;}}
function saveDeck(){localStorage.setItem('bijbelQuizDeck',JSON.stringify(cards));}
function saveKnown(){localStorage.setItem('bijbelQuizKnown',JSON.stringify([...known]));}
function render(){if(index>=cards.length)index=0;const c=cards[index];$('question').textContent=c.question;$('answer').textContent=c.answer;$('context').textContent=c.context;$('verse').textContent=c.verse;$('counter').textContent=`Kaart ${index+1} van ${cards.length}`;$('knownCount').textContent=`${known.size} gekend`;$('progressBar').style.width=`${((index+1)/cards.length)*100}%`;flashcard.classList.remove('flipped');$('status').textContent=known.has(index)?'Deze kaart heb je al als gekend gemarkeerd.':'Denk even na en draai daarna de kaart om.';localStorage.setItem('bijbelQuizIndex',index);}
function showPanel(which){const study=which==='study';$('studyPanel').hidden=!study;$('createPanel').hidden=study;$('studyTab').classList.toggle('active',study);$('createTab').classList.toggle('active',!study);$('studyTab').setAttribute('aria-selected',String(study));$('createTab').setAttribute('aria-selected',String(!study));}
flashcard.addEventListener('click',()=>{flashcard.classList.toggle('flipped');$('status').textContent=flashcard.classList.contains('flipped')?'Beoordeel je antwoord.':'Denk even na en draai daarna de kaart om.';});
$('known').addEventListener('click',()=>{known.add(index);saveKnown();render();});$('again').addEventListener('click',()=>{known.delete(index);saveKnown();render();});$('next').addEventListener('click',()=>{index=(index+1)%cards.length;render();});$('previous').addEventListener('click',()=>{index=(index-1+cards.length)%cards.length;render();});$('random').addEventListener('click',()=>{let next=index;while(cards.length>1&&next===index)next=Math.floor(Math.random()*cards.length);index=next;render();});
$('studyTab').addEventListener('click',()=>showPanel('study'));$('createTab').addEventListener('click',()=>showPanel('create'));$('accessCode').value=localStorage.getItem('bijbelQuizAccessCode')||'';
$('generatorForm').addEventListener('submit',async event=>{event.preventDefault();const topic=$('topic').value.trim();const amount=Number($('amount').value);const level=$('level').value;const audience=$('audience').value;const accessCode=$('accessCode').value;const status=$('generatorStatus');const generate=$('generate');if(!topic)return;localStorage.setItem('bijbelQuizAccessCode',accessCode);status.className='generator-status';status.textContent='Je nieuwe kaarten worden gemaakt…';generate.disabled=true;try{const response=await fetch('/.netlify/functions/generate-quiz',{method:'POST',headers:{'Content-Type':'application/json','X-Quiz-Access-Code':accessCode},body:JSON.stringify({topic,amount,level,audience})});const result=await response.json();if(!response.ok||!Array.isArray(result.cards))throw new Error(result.error||'De kaarten konden niet worden gemaakt.');cards=result.cards;index=0;known=new Set();saveKnown();saveDeck();status.textContent=`${cards.length} nieuwe kaarten over “${topic}” staan klaar.`;render();showPanel('study');}catch(error){status.className='generator-status error';status.textContent=error.message||'Er ging iets mis. Probeer het later opnieuw.';}finally{generate.disabled=false;}});
$('restoreDefault').addEventListener('click',()=>{cards=defaultCards;index=0;known=new Set();saveKnown();saveDeck();render();showPanel('study');});
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
